{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3eb35da8-4670-44bd-8bd5-c934e1d98283",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69ee1af5-ff4b-4343-966c-fa8ab8ab70fe",
   "metadata": {},
   "outputs": [],
   "source": [
    "os.environ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3e7ae87d-06fc-4ab7-994d-32eeb8a7b879",
   "metadata": {},
   "outputs": [],
   "source": [
    "migs= 'MIG-c3ce33ce-ced8-5961-bb87-2b40eb100277,MIG-280489c4-1d98-5b07-b4f6-2fc85fc874fa,MIG-c432df19-0894-5232-ac1c-9a3440fc267e,MIG-e8f61a95-352a-56cc-b95d-0c35fc14e8bf'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "44ad8724-9f7a-4aed-86ad-85cd7c576c5a",
   "metadata": {},
   "outputs": [],
   "source": [
    "env = dict(os.environ)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "864cbb81-726d-47f7-83ec-a47df00b95da",
   "metadata": {},
   "outputs": [],
   "source": [
    "env['CUDA_VISIBLE_DEVICES']=migs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c34ffce-4781-40fd-a9ac-eff59e4271dc",
   "metadata": {},
   "outputs": [],
   "source": [
    "os.environ = env"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fcce5e14-bad9-436b-ae05-65a4f2c478ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "os.environ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1c395110-6a5b-4162-9d75-7fe11bee2385",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-24 19:19:58,723\tINFO worker.py:1544 -- Started a local Ray instance. View the dashboard at \u001b[1m\u001b[32m127.0.0.1:8265 \u001b[39m\u001b[22m\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "    <div style=\"margin-left: 50px;display: flex;flex-direction: row;align-items: center\">\n",
       "        <h3 style=\"color: var(--jp-ui-font-color0)\">Ray</h3>\n",
       "        <svg version=\"1.1\" id=\"ray\" width=\"3em\" viewBox=\"0 0 144.5 144.6\" style=\"margin-left: 3em;margin-right: 3em\">\n",
       "            <g id=\"layer-1\">\n",
       "                <path fill=\"#00a2e9\" class=\"st0\" d=\"M97.3,77.2c-3.8-1.1-6.2,0.9-8.3,5.1c-3.5,6.8-9.9,9.9-17.4,9.6S58,88.1,54.8,81.2c-1.4-3-3-4-6.3-4.1\n",
       "                    c-5.6-0.1-9.9,0.1-13.1,6.4c-3.8,7.6-13.6,10.2-21.8,7.6C5.2,88.4-0.4,80.5,0,71.7c0.1-8.4,5.7-15.8,13.8-18.2\n",
       "                    c8.4-2.6,17.5,0.7,22.3,8c1.3,1.9,1.3,5.2,3.6,5.6c3.9,0.6,8,0.2,12,0.2c1.8,0,1.9-1.6,2.4-2.8c3.5-7.8,9.7-11.8,18-11.9\n",
       "                    c8.2-0.1,14.4,3.9,17.8,11.4c1.3,2.8,2.9,3.6,5.7,3.3c1-0.1,2,0.1,3,0c2.8-0.5,6.4,1.7,8.1-2.7s-2.3-5.5-4.1-7.5\n",
       "                    c-5.1-5.7-10.9-10.8-16.1-16.3C84,38,81.9,37.1,78,38.3C66.7,42,56.2,35.7,53,24.1C50.3,14,57.3,2.8,67.7,0.5\n",
       "                    C78.4-2,89,4.7,91.5,15.3c0.1,0.3,0.1,0.5,0.2,0.8c0.7,3.4,0.7,6.9-0.8,9.8c-1.7,3.2-0.8,5,1.5,7.2c6.7,6.5,13.3,13,19.8,19.7\n",
       "                    c1.8,1.8,3,2.1,5.5,1.2c9.1-3.4,17.9-0.6,23.4,7c4.8,6.9,4.6,16.1-0.4,22.9c-5.4,7.2-14.2,9.9-23.1,6.5c-2.3-0.9-3.5-0.6-5.1,1.1\n",
       "                    c-6.7,6.9-13.6,13.7-20.5,20.4c-1.8,1.8-2.5,3.2-1.4,5.9c3.5,8.7,0.3,18.6-7.7,23.6c-7.9,5-18.2,3.8-24.8-2.9\n",
       "                    c-6.4-6.4-7.4-16.2-2.5-24.3c4.9-7.8,14.5-11,23.1-7.8c3,1.1,4.7,0.5,6.9-1.7C91.7,98.4,98,92.3,104.2,86c1.6-1.6,4.1-2.7,2.6-6.2\n",
       "                    c-1.4-3.3-3.8-2.5-6.2-2.6C99.8,77.2,98.9,77.2,97.3,77.2z M72.1,29.7c5.5,0.1,9.9-4.3,10-9.8c0-0.1,0-0.2,0-0.3\n",
       "                    C81.8,14,77,9.8,71.5,10.2c-5,0.3-9,4.2-9.3,9.2c-0.2,5.5,4,10.1,9.5,10.3C71.8,29.7,72,29.7,72.1,29.7z M72.3,62.3\n",
       "                    c-5.4-0.1-9.9,4.2-10.1,9.7c0,0.2,0,0.3,0,0.5c0.2,5.4,4.5,9.7,9.9,10c5.1,0.1,9.9-4.7,10.1-9.8c0.2-5.5-4-10-9.5-10.3\n",
       "                    C72.6,62.3,72.4,62.3,72.3,62.3z M115,72.5c0.1,5.4,4.5,9.7,9.8,9.9c5.6-0.2,10-4.8,10-10.4c-0.2-5.4-4.6-9.7-10-9.7\n",
       "                    c-5.3-0.1-9.8,4.2-9.9,9.5C115,72.1,115,72.3,115,72.5z M19.5,62.3c-5.4,0.1-9.8,4.4-10,9.8c-0.1,5.1,5.2,10.4,10.2,10.3\n",
       "                    c5.6-0.2,10-4.9,9.8-10.5c-0.1-5.4-4.5-9.7-9.9-9.6C19.6,62.3,19.5,62.3,19.5,62.3z M71.8,134.6c5.9,0.2,10.3-3.9,10.4-9.6\n",
       "                    c0.5-5.5-3.6-10.4-9.1-10.8c-5.5-0.5-10.4,3.6-10.8,9.1c0,0.5,0,0.9,0,1.4c-0.2,5.3,4,9.8,9.3,10\n",
       "                    C71.6,134.6,71.7,134.6,71.8,134.6z\"/>\n",
       "            </g>\n",
       "        </svg>\n",
       "        <table>\n",
       "            <tr>\n",
       "                <td style=\"text-align: left\"><b>Python version:</b></td>\n",
       "                <td style=\"text-align: left\"><b>3.9.16</b></td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                <td style=\"text-align: left\"><b>Ray version:</b></td>\n",
       "                <td style=\"text-align: left\"><b> 2.3.0</b></td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "    <td style=\"text-align: left\"><b>Dashboard:</b></td>\n",
       "    <td style=\"text-align: left\"><b><a href=\"http://127.0.0.1:8265\" target=\"_blank\">http://127.0.0.1:8265</a></b></td>\n",
       "</tr>\n",
       "\n",
       "        </table>\n",
       "    </div>\n",
       "</div>\n"
      ],
      "text/plain": [
       "RayContext(dashboard_url='127.0.0.1:8265', python_version='3.9.16', ray_version='2.3.0', ray_commit='cf7a56b4b0b648c324722df7c99c168e92ff0b45', address_info={'node_ip_address': '127.0.0.1', 'raylet_ip_address': '127.0.0.1', 'redis_address': None, 'object_store_address': 'tcp://127.0.0.1:65497', 'raylet_socket_name': 'tcp://127.0.0.1:65391', 'webui_url': '127.0.0.1:8265', 'session_dir': 'C:\\\\Users\\\\chper\\\\AppData\\\\Local\\\\Temp\\\\ray\\\\session_2023-02-24_19-19-56_532952_1096', 'metrics_export_port': 65488, 'gcs_address': '127.0.0.1:65315', 'address': '127.0.0.1:65315', 'dashboard_agent_listen_port': 52365, 'node_id': '98593d24672d170187475b91f442a1dddd465253855c81532cf13bde'})"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "import ray\n",
    "\n",
    "# Set CUDA_VISIBLE_DEVICES to control which GPUs are visible to Ray\n",
    "#os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"0,1,2,3,4,5,6\"#'MIG-c3ce33ce-ced8-5961-bb87-2b40eb100277,MIG-280489c4-1d98-5b07-b4f6-2fc85fc874fa,MIG-c432df19-0894-5232-ac1c-9a3440fc267e,MIG-e8f61a95-352a-56cc-b95d-0c35fc14e8bf'#\"0,1,2,3,4,5,6\"\n",
    "\n",
    "# Initialize Ray with the appropriate configuration\n",
    "ray.init()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b80f44a6-e129-4e02-b394-ae99d0c8d8d4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'object_store_memory': 1053027532.0, 'CPU': 20.0, 'GPU': 1.0, 'node:127.0.0.1': 1.0, 'memory': 2106055067.0}\n"
     ]
    }
   ],
   "source": [
    "resources = ray.cluster_resources()\n",
    "print(resources)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "939af842",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:561: calling function (from tensorflow.python.eager.def_function) with experimental_relax_shapes is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "experimental_relax_shapes is deprecated, use reduce_retracing instead\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import gym\n",
    "from gym_CTgraph import CTgraph_env\n",
    "from gym_CTgraph.CTgraph_plot import CTgraph_plot\n",
    "from gym_CTgraph.CTgraph_conf import CTgraph_conf\n",
    "from gym_CTgraph.CTgraph_images import CTgraph_images\n",
    "import json\n",
    "import argparse\n",
    "#import json\n",
    "import random\n",
    "import matplotlib.pyplot as plt\n",
    "import timeit\n",
    "\n",
    "from gym.spaces import Box, Discrete, Dict\n",
    "from ray.tune.registry import register_env\n",
    "from ray import tune\n",
    "\n",
    "from PIL import Image\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.image as mpimg\n",
    "\n",
    "import argparse\n",
    "import gym\n",
    "from gym.spaces import Discrete, Box\n",
    "import numpy as np\n",
    "#import os\n",
    "import random\n",
    "\n",
    "import ray\n",
    "from ray import tune\n",
    "from ray.rllib.agents import ppo\n",
    "from ray.rllib.env.env_context import EnvContext\n",
    "from ray.rllib.models import ModelCatalog\n",
    "from ray.rllib.models.tf.tf_modelv2 import TFModelV2\n",
    "from ray.rllib.models.tf.fcnet import FullyConnectedNetwork\n",
    "from ray.rllib.models.torch.torch_modelv2 import TorchModelV2\n",
    "from ray.rllib.models.torch.fcnet import FullyConnectedNetwork as TorchFC\n",
    "from ray.rllib.utils.framework import try_import_tf, try_import_torch\n",
    "from ray.rllib.utils.test_utils import check_learning_achieved\n",
    "from ray.tune.logger import pretty_print"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "51502519-f453-4da2-9311-c81f67f0d7c7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'import ray\\nray.init()\\nresources = ray.cluster_resources()\\nprint(resources)'"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'''import ray\n",
    "ray.init()\n",
    "resources = ray.cluster_resources()\n",
    "print(resources)'''\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7a94b421",
   "metadata": {},
   "outputs": [],
   "source": [
    "from ray import tune"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "a3278362",
   "metadata": {},
   "outputs": [],
   "source": [
    "def env_creator(env_config={}):\n",
    "    # fetch the parameters from the json file\n",
    "    configuration = CTgraph_conf(\"/home/lunet/cocp5/Documents/rllib20/graph09.json\")\n",
    "    conf_data = configuration.getParameters()\n",
    "    # print configration data\n",
    "    print(json.dumps(conf_data, indent=3))\n",
    "    env = gym.make('CTgraph-v0')\n",
    "    # instantiate the maze\n",
    "    #start = timeit.timeit()\n",
    "    #env = gym.make('CTgraph-v0')\n",
    "    #end = timeit.timeit()\n",
    "    #print(end - start)\n",
    "\n",
    "    imageDataset = CTgraph_images(conf_data)\n",
    "    observation = env.init(conf_data, imageDataset)\n",
    "\n",
    "    # get a random path from the maze\n",
    "    #high_reward_path = np.array(np.random.randint(1, conf_data['graph_shape']['branching_factor'], size=conf_data['graph_shape']['depth']))\n",
    "    # use this random path to set the path to the high reward. Note that the maze would have already a high_reward_path from the initialisation\n",
    "    #env.set_high_reward_path(high_reward_path)\n",
    "    #seed_everything(env)  \n",
    "    \n",
    "    return env"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "31213ad4",
   "metadata": {},
   "outputs": [],
   "source": [
    "register_env(\"CT-Graph_d2_b2_wp05_crv0_MDP\", env_creator)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "e3129fc7",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div class=\"tuneStatus\">\n",
       "  <div style=\"display: flex;flex-direction: row\">\n",
       "    <div style=\"display: flex;flex-direction: column;\">\n",
       "      <h3>Tune Status</h3>\n",
       "      <table>\n",
       "<tbody>\n",
       "<tr><td>Current time:</td><td>2023-02-24 19:20:40</td></tr>\n",
       "<tr><td>Running for: </td><td>00:00:21.17        </td></tr>\n",
       "<tr><td>Memory:      </td><td>15.2/15.7 GiB      </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "    <div class=\"systemInfo\">\n",
       "      <h3>System Info</h3>\n",
       "      Using FIFO scheduling algorithm.<br>Resources requested: 0/20 CPUs, 0/1 GPUs, 0.0/1.96 GiB heap, 0.0/0.98 GiB objects\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "<div class=\"messages\">\n",
       "  <h3>Messages</h3>\n",
       "  : ***LOW MEMORY*** less than 10% of the memory on this node is available for use. This can cause unexpected crashes. Consider reducing the memory used by your application or reducing the Ray object store size by setting `object_store_memory` when calling `ray.init`.\n",
       "  \n",
       "  Number of errored trials: 1<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                                    </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                        </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DDPPO_CT-Graph_d2_b2_wp05_crv0_MDP_466ff_00000</td><td style=\"text-align: right;\">           1</td><td>C:\\CT-Graph_Native_Experiments\\CT-Graph_d2_b2_wp05_crv0_MDP04\\DDPPO\\DDPPO_CT-Graph_d2_b2_wp05_crv0_MDP_466ff_00000_0_2023-02-24_19-20-19\\error.txt</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".messages {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  padding-left: 1em;\n",
       "  overflow-y: auto;\n",
       "}\n",
       ".messages h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n",
       "\n",
       "  </div>\n",
       "  <div class=\"hDivider\"></div>\n",
       "  <div class=\"trialStatus\">\n",
       "    <h3>Trial Status</h3>\n",
       "    <table>\n",
       "<thead>\n",
       "<tr><th>Trial name                                    </th><th>status  </th><th>loc  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DDPPO_CT-Graph_d2_b2_wp05_crv0_MDP_466ff_00000</td><td>ERROR   </td><td>     </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "  </div>\n",
       "</div>\n",
       "<style>\n",
       ".tuneStatus {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".tuneStatus .systemInfo {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       ".tuneStatus .trialStatus {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".tuneStatus .hDivider {\n",
       "  border-bottom-width: var(--jp-border-width);\n",
       "  border-bottom-color: var(--jp-border-color0);\n",
       "  border-bottom-style: solid;\n",
       "}\n",
       ".tuneStatus .vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-24 19:20:18,953\tWARNING deprecation.py:50 -- DeprecationWarning: `AlgorithmConfig.evaluation(evaluation_num_episodes=..)` has been deprecated. Use `AlgorithmConfig.evaluation(evaluation_duration=.., evaluation_duration_unit='episodes')` instead. This will raise an error in the future!\n",
      "\u001b[2m\u001b[36m(pid=10052)\u001b[0m WARNING:tensorflow:From C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:561: calling function (from tensorflow.python.eager.def_function) with experimental_relax_shapes is deprecated and will be removed in a future version.\n",
      "\u001b[2m\u001b[36m(pid=10052)\u001b[0m Instructions for updating:\n",
      "\u001b[2m\u001b[36m(pid=10052)\u001b[0m experimental_relax_shapes is deprecated, use reduce_retracing instead\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m 2023-02-24 19:20:32,601\tWARNING algorithm_config.py:596 -- Cannot create DDPPOConfig from given `config_dict`! Property __stdout_file__ not supported.\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m 2023-02-24 19:20:32,602\tWARNING deprecation.py:50 -- DeprecationWarning: `AlgorithmConfig.evaluation(evaluation_num_episodes=..)` has been deprecated. Use `AlgorithmConfig.evaluation(evaluation_duration=.., evaluation_duration_unit='episodes')` instead. This will raise an error in the future!\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m 2023-02-24 19:20:33,341\tINFO algorithm.py:506 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=11528)\u001b[0m WARNING:tensorflow:From C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:561: calling function (from tensorflow.python.eager.def_function) with experimental_relax_shapes is deprecated and will be removed in a future version.\n",
      "\u001b[2m\u001b[36m(pid=11528)\u001b[0m Instructions for updating:\n",
      "\u001b[2m\u001b[36m(pid=11528)\u001b[0m experimental_relax_shapes is deprecated, use reduce_retracing instead\n",
      "\u001b[2m\u001b[36m(pid=33556)\u001b[0m WARNING:tensorflow:From C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:561: calling function (from tensorflow.python.eager.def_function) with experimental_relax_shapes is deprecated and will be removed in a future version.\n",
      "\u001b[2m\u001b[36m(pid=33556)\u001b[0m Instructions for updating:\n",
      "\u001b[2m\u001b[36m(pid=33556)\u001b[0m experimental_relax_shapes is deprecated, use reduce_retracing instead\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m ---------------------------------------------------\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m              The CT-graph environments             \n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m ---------------------------------------------------\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m Reading configuration parameters from  /home/lunet/cocp5/Documents/rllib20/graph09.json\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m 2023-02-24 19:20:40,011\tERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=33556, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000184C8AC7460>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 607, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m     self.env = env_creator(copy.deepcopy(self.env_context))\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m   File \"C:\\Users\\chper\\AppData\\Local\\Temp\\ipykernel_1096\\2195653809.py\", line 3, in env_creator\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m   File \"C:\\CT-Graph_Native_Experiments\\gym_CTgraph\\CTgraph_conf.py\", line 10, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m     with open(file, 'r') as f:\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=33556)\u001b[0m FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "2023-02-24 19:20:40,095\tERROR trial_runner.py:1062 -- Trial DDPPO_CT-Graph_d2_b2_wp05_crv0_MDP_466ff_00000: Error processing event.\n",
      "ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\tune\\execution\\ray_trial_executor.py\", line 1276, in get_next_executor_event\n",
      "    future_result = ray.get(ready_future)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\worker.py\", line 2382, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::DDPPO.__init__()\u001b[39m (pid=10052, ip=127.0.0.1, repr=DDPPO)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 240, in _setup\n",
      "    self.add_workers(\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 614, in add_workers\n",
      "    raise result.get()\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py\", line 477, in __fetch_result\n",
      "    result = ray.get(r)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\worker.py\", line 2382, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=11528, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000224F4497430>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 607, in __init__\n",
      "    self.env = env_creator(copy.deepcopy(self.env_context))\n",
      "  File \"C:\\Users\\chper\\AppData\\Local\\Temp\\ipykernel_1096\\2195653809.py\", line 3, in env_creator\n",
      "  File \"C:\\CT-Graph_Native_Experiments\\gym_CTgraph\\CTgraph_conf.py\", line 10, in __init__\n",
      "    with open(file, 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::DDPPO.__init__()\u001b[39m (pid=10052, ip=127.0.0.1, repr=DDPPO)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 902, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 445, in __init__\n",
      "    super().__init__(\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 169, in __init__\n",
      "    self.setup(copy.deepcopy(self.config))\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\ddppo\\ddppo.py\", line 226, in setup\n",
      "    super().setup(config)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 571, in setup\n",
      "    self.workers = WorkerSet(\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 192, in __init__\n",
      "    raise e.args[0].args[2]\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div class=\"trialProgress\">\n",
       "  <h3>Trial Progress</h3>\n",
       "  <table>\n",
       "<thead>\n",
       "<tr><th>Trial name                                    </th><th>trial_id   </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>DDPPO_CT-Graph_d2_b2_wp05_crv0_MDP_466ff_00000</td><td>466ff_00000</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".trialProgress {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".trialProgress h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".trialProgress td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m 2023-02-24 19:20:40,065\tERROR actor_manager.py:496 -- Ray error, taking actor 1 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=11528, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000224F4497430>)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 607, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     self.env = env_creator(copy.deepcopy(self.env_context))\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\AppData\\Local\\Temp\\ipykernel_1096\\2195653809.py\", line 3, in env_creator\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\CT-Graph_Native_Experiments\\gym_CTgraph\\CTgraph_conf.py\", line 10, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     with open(file, 'r') as f:\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m 2023-02-24 19:20:40,066\tERROR actor_manager.py:496 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=33556, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000184C8AC7460>)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 607, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     self.env = env_creator(copy.deepcopy(self.env_context))\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\AppData\\Local\\Temp\\ipykernel_1096\\2195653809.py\", line 3, in env_creator\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\CT-Graph_Native_Experiments\\gym_CTgraph\\CTgraph_conf.py\", line 10, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     with open(file, 'r') as f:\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m 2023-02-24 19:20:40,069\tERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::DDPPO.__init__()\u001b[39m (pid=10052, ip=127.0.0.1, repr=DDPPO)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 240, in _setup\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     self.add_workers(\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 614, in add_workers\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     raise result.get()\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py\", line 477, in __fetch_result\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     result = ray.get(r)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\worker.py\", line 2382, in get\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     raise value\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=11528, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000224F4497430>)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 607, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     self.env = env_creator(copy.deepcopy(self.env_context))\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\AppData\\Local\\Temp\\ipykernel_1096\\2195653809.py\", line 3, in env_creator\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\CT-Graph_Native_Experiments\\gym_CTgraph\\CTgraph_conf.py\", line 10, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     with open(file, 'r') as f:\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m \n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m \n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m \u001b[36mray::DDPPO.__init__()\u001b[39m (pid=10052, ip=127.0.0.1, repr=DDPPO)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 902, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 445, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     super().__init__(\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 169, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     self.setup(copy.deepcopy(self.config))\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\ddppo\\ddppo.py\", line 226, in setup\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     super().setup(config)\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 571, in setup\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     self.workers = WorkerSet(\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 192, in __init__\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m     raise e.args[0].args[2]\n",
      "\u001b[2m\u001b[36m(DDPPO pid=10052)\u001b[0m FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m 2023-02-24 19:20:40,057\tERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=11528, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000224F4497430>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m   File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 607, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m     self.env = env_creator(copy.deepcopy(self.env_context))\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m   File \"C:\\Users\\chper\\AppData\\Local\\Temp\\ipykernel_1096\\2195653809.py\", line 3, in env_creator\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m   File \"C:\\CT-Graph_Native_Experiments\\gym_CTgraph\\CTgraph_conf.py\", line 10, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m     with open(file, 'r') as f:\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "2023-02-24 19:20:40,134\tERROR ray_trial_executor.py:930 -- An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\tune\\execution\\ray_trial_executor.py\", line 921, in _resolve_stop_event\n",
      "    ray.get(future, timeout=timeout)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\worker.py\", line 2382, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::DDPPO.__init__()\u001b[39m (pid=10052, ip=127.0.0.1, repr=DDPPO)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 240, in _setup\n",
      "    self.add_workers(\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 614, in add_workers\n",
      "    raise result.get()\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py\", line 477, in __fetch_result\n",
      "    result = ray.get(r)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 105, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\worker.py\", line 2382, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=11528, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000224F4497430>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 607, in __init__\n",
      "    self.env = env_creator(copy.deepcopy(self.env_context))\n",
      "  File \"C:\\Users\\chper\\AppData\\Local\\Temp\\ipykernel_1096\\2195653809.py\", line 3, in env_creator\n",
      "  File \"C:\\CT-Graph_Native_Experiments\\gym_CTgraph\\CTgraph_conf.py\", line 10, in __init__\n",
      "    with open(file, 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::DDPPO.__init__()\u001b[39m (pid=10052, ip=127.0.0.1, repr=DDPPO)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 902, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 803, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 674, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 445, in __init__\n",
      "    super().__init__(\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 169, in __init__\n",
      "    self.setup(copy.deepcopy(self.config))\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 466, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\ddppo\\ddppo.py\", line 226, in setup\n",
      "    super().setup(config)\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 571, in setup\n",
      "    self.workers = WorkerSet(\n",
      "  File \"C:\\Users\\chper\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 192, in __init__\n",
      "    raise e.args[0].args[2]\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/lunet/cocp5/Documents/rllib20/graph09.json'\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m ---------------------------------------------------\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m              The CT-graph environments             \n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m ---------------------------------------------------\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=11528)\u001b[0m Reading configuration parameters from  /home/lunet/cocp5/Documents/rllib20/graph09.json\n"
     ]
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [DDPPO_CT-Graph_d2_b2_wp05_crv0_MDP_466ff_00000])",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[8], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mtune\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mDDPPO\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m      2\u001b[0m \u001b[43m             \u001b[49m\u001b[38;5;66;43;03m# algorithm specific configuration\u001b[39;49;00m\n\u001b[0;32m      3\u001b[0m \u001b[43m             \u001b[49m\u001b[43mconfig\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43menv\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mCT-Graph_d2_b2_wp05_crv0_MDP\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m#\u001b[39;49;00m\n\u001b[0;32m      4\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mframework\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mtorch\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m      5\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mseed\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[38;5;241;43m958\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m      6\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;66;43;03m#\"num_gpus\": 7,\"num_rollout_workers\": 1,\u001b[39;49;00m\n\u001b[0;32m      7\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mnum_envs_per_worker\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m      8\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mnum_gpus_per_worker\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m      9\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mtrain_batch_size\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m128\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     10\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43muse_critic\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m     11\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43muse_gae\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m     12\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mlambda\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0.99\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     13\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43msgd_minibatch_size\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m64\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     14\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mnum_sgd_iter\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m8\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     15\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mshuffle_sequences\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m     16\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mentropy_coeff\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0.00015\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     17\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mclip_param\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0.1\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     18\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mgrad_clip\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     19\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mlr\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0.0015\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     20\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;66;43;03m#\"num_cpus_per_worker\": 1,\u001b[39;49;00m\n\u001b[0;32m     21\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;66;43;03m#\"model\": {\"custom_model\": \"pa_model\", },\u001b[39;49;00m\n\u001b[0;32m     22\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mevaluation_interval\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     23\u001b[0m \u001b[43m                     \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mevaluation_num_episodes\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m2\u001b[39;49m\n\u001b[0;32m     24\u001b[0m \u001b[43m                     \u001b[49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     25\u001b[0m \u001b[43m             \u001b[49m\u001b[43mlocal_dir\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mCT-Graph_d2_b2_wp05_crv0_MDP04\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# directory to save results\u001b[39;49;00m\n\u001b[0;32m     26\u001b[0m \u001b[43m             \u001b[49m\u001b[43mcheckpoint_freq\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m2\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# frequency between checkpoints\u001b[39;49;00m\n\u001b[0;32m     27\u001b[0m \u001b[43m             \u001b[49m\u001b[43mkeep_checkpoints_num\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m6\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     28\u001b[0m \u001b[43m             \u001b[49m\u001b[43mstop\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mtimesteps_total\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1024000\u001b[39;49m\u001b[43m}\u001b[49m\n\u001b[0;32m     29\u001b[0m \u001b[43m             \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\rllib20c\\lib\\site-packages\\ray\\tune\\tune.py:792\u001b[0m, in \u001b[0;36mrun\u001b[1;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, chdir_to_trial_dir, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, reuse_actors, raise_on_failed_trial, callbacks, max_concurrent_trials, trial_executor, _experiment_checkpoint_dir, _remote, _remote_string_queue)\u001b[0m\n\u001b[0;32m    790\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m incomplete_trials:\n\u001b[0;32m    791\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m raise_on_failed_trial \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m experiment_interrupted_event\u001b[38;5;241m.\u001b[39mis_set():\n\u001b[1;32m--> 792\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m TuneError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTrials did not complete\u001b[39m\u001b[38;5;124m\"\u001b[39m, incomplete_trials)\n\u001b[0;32m    793\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    794\u001b[0m         logger\u001b[38;5;241m.\u001b[39merror(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTrials did not complete: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, incomplete_trials)\n",
      "\u001b[1;31mTuneError\u001b[0m: ('Trials did not complete', [DDPPO_CT-Graph_d2_b2_wp05_crv0_MDP_466ff_00000])"
     ]
    }
   ],
   "source": [
    "tune.run(\"DDPPO\",\n",
    "             # algorithm specific configuration\n",
    "             config={\"env\": \"CT-Graph_d2_b2_wp05_crv0_MDP\",  #\n",
    "                     \"framework\": \"torch\",\n",
    "                     \"seed\":958,\n",
    "                     #\"num_gpus\": 7,\"num_rollout_workers\": 1,\n",
    "                     \"num_envs_per_worker\": 1,\n",
    "                     \"num_gpus_per_worker\": 0,\n",
    "                     \"train_batch_size\": 128,\n",
    "                     \"use_critic\":True,\n",
    "                     \"use_gae\": True,\n",
    "                     \"lambda\": 0.99,\n",
    "                     \"sgd_minibatch_size\": 64,\n",
    "                     \"num_sgd_iter\": 8,\n",
    "                     \"shuffle_sequences\": False,\n",
    "                     \"entropy_coeff\": 0.00015,\n",
    "                     \"clip_param\": 0.1,\n",
    "                     \"grad_clip\": 5,\n",
    "                     \"lr\": 0.0015,\n",
    "                     #\"num_cpus_per_worker\": 1,\n",
    "                     #\"model\": {\"custom_model\": \"pa_model\", },\n",
    "                     \"evaluation_interval\": 1,\n",
    "                     \"evaluation_num_episodes\": 2\n",
    "                     },\n",
    "             local_dir=\"CT-Graph_d2_b2_wp05_crv0_MDP04\",  # directory to save results\n",
    "             checkpoint_freq=2,  # frequency between checkpoints\n",
    "             keep_checkpoints_num=6,\n",
    "             stop={\"timesteps_total\": 1024000}\n",
    "             )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64bee6a0-fbb5-4ff4-a955-c31597ed6ba9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
